name: Sync Git Folder

on:
  workflow_run:
    workflows: ["Build"]   
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # only if build succeeds
    runs-on: ubuntu-latest
    name: 'Update git folder'
    environment: dev
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Upload notebooks to Databricks workspace
        run: |
          databricks workspace import-dir \
            ./mydatabrickscodes \
            /Workspace/Sonjoy \
            --overwrite
