name: Run Databricks Notebook on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Run notebook on ephemeral cluster
        uses: databricks/run-notebook@v0.0.3
        with:
          run-name: "PR Trigger Run"
          workspace-notebook-path: "/Workspace/Sonjoy/processing/products/myfirstingestionnotebook"
          new-cluster-json: |
            {
              "spark_version": "13.3.x-scala2.12",
              "node_type_id": "Standard_DS3_v2",
              "num_workers": 1
            }
