name: Run Databricks Notebook on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Run notebook via Databricks action
        uses: databricks/run-notebook@v0.0.3
        with:
          # Use workspace path of your notebook
          workspace-notebook-path: '/Workspace/Sonjoy/processing/products/myfirstingestionnotebook'
          run-name: 'PR Trigger Run'
          new-cluster: |
            {
              "spark_version": "13.3.x-scala2.12",
              "node_type_id": "Standard_DS3_v2",
              "num_workers": 2
            }
